theme: jekyll-theme-minimal
layout: home
title: Resume
description: Please check my README file to see how to host your resume on Github pages.
author: Heejeong Kim
published: true
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
