theme: daattali/beautiful-jekyll
layout: home
title: Resume
description: Check my README file to see how to host your own resume on Github pages
author: Heejeong Kim
published: true
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
