theme: jekyll-theme-minimal
layout: home
title: Resume
description: Please view my resume.
author: Heejeong Kim
published: true
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
